global:
  scrape_interval: 15s # Intervalo de captura de métricas
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'hosting_guard'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:8000']
