"""
GitHub Deploy Diagnostics Matrix — Fase 1.

Single source of truth for all supported deploy error codes, their stages,
user-facing messages, and operational metadata.

Usage:
    from app.services.deploy.diagnostics_matrix import get_matrix_entry, SUPPORTED_CODES
    entry = get_matrix_entry("node_sass_incompatible")
"""
from typing import Optional

MATRIX: dict = {
    # ── Validation ─────────────────────────────────────────────────────────────
    "invalid_repo_url": {
        "stage": "validation",
        "severity": "warning",
        "detail": "La URL del repositorio no es válida.",
        "suggested_fix": "Usá una URL de GitHub válida, por ejemplo https://github.com/usuario/repo.git",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "subdomain_already_exists": {
        "stage": "validation",
        "severity": "warning",
        "detail": "Ese nombre de proyecto ya está en uso.",
        "suggested_fix": "Elegí otro nombre o eliminá el sitio anterior.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "deploy_runtime_missing_tool": {
        "stage": "validation",
        "severity": "high",
        "detail": "Una herramienta requerida no está disponible en el entorno de deploy.",
        "suggested_fix": "Contactá soporte técnico.",
        "retryable": False,
        "requires_user_action": False,
        "requires_admin_action": True,
    },
    "deploy_rate_limit_exceeded": {
        "stage": "validation",
        "severity": "info",
        "detail": "Alcanzaste el límite de deploys por hora.",
        "suggested_fix": "Esperá unos minutos antes de intentar nuevamente.",
        "retryable": True,
        "requires_user_action": False,
        "requires_admin_action": False,
    },

    # ── Clone ───────────────────────────────────────────────────────────────────
    "github_repo_not_found": {
        "stage": "clone",
        "severity": "warning",
        "detail": "No pudimos encontrar el repositorio.",
        "suggested_fix": "Verificá que la URL sea correcta y que el repositorio sea público.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "github_private_repo_unauthorized": {
        "stage": "clone",
        "severity": "warning",
        "detail": "No tenemos permisos para clonar este repositorio.",
        "suggested_fix": "Hacé público el repositorio o conectá permisos de GitHub.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "github_branch_not_found": {
        "stage": "clone",
        "severity": "warning",
        "detail": "No encontramos la branch indicada.",
        "suggested_fix": "Verificá que la branch exista. Por ejemplo: main o master.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "github_clone_failed": {
        "stage": "clone",
        "severity": "warning",
        "detail": "No pudimos clonar el repositorio.",
        "suggested_fix": "Verificá que la URL sea correcta, que el repo exista y que sea público.",
        "retryable": True,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "github_clone_timeout": {
        "stage": "clone",
        "severity": "warning",
        "detail": "El repositorio tardó demasiado en clonarse.",
        "suggested_fix": "Reintentá o verificá el tamaño/disponibilidad del repositorio.",
        "retryable": True,
        "requires_user_action": False,
        "requires_admin_action": False,
    },

    # ── Project detection ────────────────────────────────────────────────────
    "package_json_not_found": {
        "stage": "project_detection",
        "severity": "warning",
        "detail": "No encontramos package.json en una ubicación soportada.",
        "suggested_fix": "Indicá el Root Directory correcto o verificá que el repo contenga una app web.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "no_web_buildable_project": {
        "stage": "project_detection",
        "severity": "warning",
        "detail": "No encontramos una app web desplegable.",
        "suggested_fix": "El repo debe contener una app frontend con script build y dependencias web (react, vite, next, etc.).",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "multiple_project_roots_detected": {
        "stage": "project_detection",
        "severity": "warning",
        "detail": "Encontramos varias apps posibles.",
        "suggested_fix": "Elegí el Root Directory correcto en la configuración avanzada.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "build_script_missing": {
        "stage": "project_detection",
        "severity": "warning",
        "detail": "El package.json no tiene script build.",
        "suggested_fix": "Agregá un script build o configurá el Build Command manualmente.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "framework_not_supported": {
        "stage": "project_detection",
        "severity": "warning",
        "detail": "Detectamos un framework que todavía no está soportado automáticamente.",
        "suggested_fix": "Configurá manualmente build/output o usá un framework soportado.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },

    # ── Dependency preflight ─────────────────────────────────────────────────
    "node_sass_incompatible": {
        "stage": "dependency_preflight",
        "severity": "warning",
        "detail": "El proyecto usa node-sass, una dependencia antigua incompatible con Node 20.",
        "suggested_fix": "Migrá de node-sass a sass (npm install sass). node-sass no es compatible con versiones modernas de Node.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "package_manager_pnpm_detected": {
        "stage": "dependency_preflight",
        "severity": "warning",
        "detail": "(legacy) El proyecto usa pnpm — ahora soportado automáticamente.",
        "suggested_fix": "Asegurate de tener pnpm-lock.yaml commiteado.",
        "retryable": True,
        "requires_user_action": False,
        "requires_admin_action": False,
    },
    "package_manager_yarn_detected": {
        "stage": "dependency_preflight",
        "severity": "warning",
        "detail": "(legacy) El proyecto usa Yarn — ahora soportado automáticamente.",
        "suggested_fix": "Asegurate de tener yarn.lock commiteado.",
        "retryable": True,
        "requires_user_action": False,
        "requires_admin_action": False,
    },
    "multiple_lockfiles_detected": {
        "stage": "dependency_preflight",
        "severity": "warning",
        "detail": "El proyecto contiene múltiples lockfiles. Dejá solo uno para evitar instalaciones inconsistentes.",
        "suggested_fix": "Eliminá los lockfiles que no correspondan al package manager que uses.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "lockfile_required": {
        "stage": "dependency_preflight",
        "severity": "warning",
        "detail": "Por seguridad, HostingGuard requiere un lockfile para instalar dependencias.",
        "suggested_fix": "Ejecutá 'npm install', 'pnpm install', o 'yarn install' localmente y commiteá el lockfile.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "node_version_mismatch": {
        "stage": "dependency_preflight",
        "severity": "warning",
        "detail": "El proyecto declara una versión de Node incompatible con el entorno de build.",
        "suggested_fix": "Actualizá las dependencias para ser compatibles con Node 20.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "next_ssr_not_supported": {
        "stage": "dependency_preflight",
        "severity": "warning",
        "detail": "El proyecto usa Next.js en modo SSR. Este hosting solo sirve sitios estáticos.",
        "suggested_fix": "Para hosting estático, agregá output: 'export' en next.config.js. Si necesitás SSR/API routes, usá el Start Command con un runtime Node.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "npm_supply_chain_tanstack_compromise": {
        "stage": "dependency_preflight",
        "severity": "critical",
        "detail": "El proyecto referencia paquetes involucrados en el compromiso de la cadena de suministro de TanStack (2026-05-11). El deploy fue bloqueado por seguridad.",
        "suggested_fix": "Actualizá los paquetes @tanstack afectados a la última versión parcheada y regenerá el lockfile con 'npm install'.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "npm_lockfile_required_for_supply_chain_safety": {
        "stage": "dependency_preflight",
        "severity": "critical",
        "detail": "El proyecto incluye @tanstack/* pero no tiene lockfile. Sin lockfile no se pueden verificar las versiones contra el compromiso de cadena de suministro de TanStack (2026-05-11).",
        "suggested_fix": "Ejecutá 'npm install' localmente para generar un package-lock.json, verificá las versiones de @tanstack/* y commiteá el lockfile.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },

    "npm_supply_chain_risk": {
        "stage": "dependency_preflight",
        "severity": "critical",
        "detail": "El deploy fue bloqueado porque el proyecto puede referenciar paquetes involucrados en un compromiso de cadena de suministro npm.",
        "suggested_fix": "Revisá las dependencias del proyecto contra los avisos de seguridad activos y actualizá a versiones seguras.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },

    # ── Dependency install ────────────────────────────────────────────────────
    "npm_install_failed": {
        "stage": "dependency_install",
        "severity": "warning",
        "detail": "El comando de instalación de dependencias falló.",
        "suggested_fix": "Ejecutá npm install localmente y corregí los errores antes de deployar.",
        "retryable": True,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "npm_ci_failed": {
        "stage": "dependency_install",
        "severity": "warning",
        "detail": "npm ci falló. El lockfile puede estar desactualizado o contener conflictos.",
        "suggested_fix": "Ejecutá 'npm install' localmente para actualizar package-lock.json, verificá los errores y commiteá el resultado.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "pnpm_install_failed": {
        "stage": "dependency_install",
        "severity": "warning",
        "detail": "pnpm install --frozen-lockfile falló.",
        "suggested_fix": "Ejecutá 'pnpm install' localmente para actualizar pnpm-lock.yaml y commiteá el resultado.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "yarn_install_failed": {
        "stage": "dependency_install",
        "severity": "warning",
        "detail": "yarn install --immutable falló.",
        "suggested_fix": "Ejecutá 'yarn install' localmente para actualizar yarn.lock y commiteá el resultado.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "npm_peer_dependency_failed": {
        "stage": "dependency_install",
        "severity": "warning",
        "detail": "Las dependencias tienen conflictos de peer dependencies.",
        "suggested_fix": "Actualizá las dependencias o ejecutá npm install --legacy-peer-deps.",
        "retryable": True,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "npm_peer_dependency_conflict": {
        "stage": "dependency_install",
        "severity": "warning",
        "detail": "npm encontró conflictos de peer dependencies.",
        "suggested_fix": "Revisá las versiones o probá instalar con legacy peer deps.",
        "retryable": True,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "dependency_version_not_found": {
        "stage": "dependency_install",
        "severity": "warning",
        "detail": "Una dependencia solicita una versión que no existe o no está disponible.",
        "suggested_fix": "Revisá package.json/package-lock.json y asegurate que las versiones existan en npm.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "npm_install_timeout": {
        "stage": "dependency_install",
        "severity": "warning",
        "detail": "La instalación de dependencias tardó demasiado.",
        "suggested_fix": "Revisá dependencias pesadas o el lockfile.",
        "retryable": True,
        "requires_user_action": False,
        "requires_admin_action": False,
    },
    "native_dependency_build_failed": {
        "stage": "dependency_install",
        "severity": "warning",
        "detail": "No pudimos compilar una dependencia nativa de Node.",
        "suggested_fix": "Este proyecto usa una dependencia que requiere compilación nativa. Actualizá las dependencias a versiones modernas.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "native_build_tool_missing": {
        "stage": "dependency_install",
        "severity": "high",
        "detail": "Faltan herramientas de compilación nativas en el entorno de build.",
        "suggested_fix": "El administrador debe agregar herramientas de compilación a la imagen de build (python3, make, g++).",
        "retryable": False,
        "requires_user_action": False,
        "requires_admin_action": True,
    },

    # ── Build ─────────────────────────────────────────────────────────────────
    "build_failed": {
        "stage": "build",
        "severity": "warning",
        "detail": "El comando de build falló.",
        "suggested_fix": "Ejecutá npm run build localmente y corregí los errores.",
        "retryable": True,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "module_not_found_build": {
        "stage": "build",
        "severity": "warning",
        "detail": "El build falló porque no se encontró un módulo/import.",
        "suggested_fix": "Revisá imports y dependencias.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "openssl_build_failed": {
        "stage": "build",
        "severity": "warning",
        "detail": "El build falló por incompatibilidad OpenSSL/Node.",
        "suggested_fix": "Usá NODE_OPTIONS=--openssl-legacy-provider o actualizá las dependencias a versiones compatibles con Node 20.",
        "retryable": True,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "env_var_missing": {
        "stage": "build",
        "severity": "warning",
        "detail": "El build parece requerir variables de entorno que no están configuradas.",
        "suggested_fix": "Configurá las variables necesarias antes de deployar.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "case_sensitive_import_error": {
        "stage": "build",
        "severity": "warning",
        "detail": "El build falló por diferencias de mayúsculas/minúsculas en imports.",
        "suggested_fix": "Linux distingue mayúsculas/minúsculas. Revisá rutas/imports.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "build_timeout": {
        "stage": "build",
        "severity": "warning",
        "detail": "El build tardó demasiado.",
        "suggested_fix": "Optimizá el build o revisá dependencias pesadas.",
        "retryable": True,
        "requires_user_action": False,
        "requires_admin_action": False,
    },

    # ── Artifact detection ────────────────────────────────────────────────────
    "index_html_not_found": {
        "stage": "artifact_detection",
        "severity": "warning",
        "detail": "No encontramos index.html en el resultado del build.",
        "suggested_fix": "Verificá que el build genere una app estática con index.html.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "output_directory_missing": {
        "stage": "artifact_detection",
        "severity": "warning",
        "detail": "No encontramos la carpeta de salida del build.",
        "suggested_fix": "Verificá el output directory: dist, build u out.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "multiple_output_directories": {
        "stage": "artifact_detection",
        "severity": "warning",
        "detail": "Encontramos múltiples salidas posibles del build.",
        "suggested_fix": "Indicá Output Directory manualmente en la configuración avanzada.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "unsafe_publish_root": {
        "stage": "artifact_detection",
        "severity": "high",
        "detail": "El directorio seleccionado parece ser el repo fuente, no el build final.",
        "suggested_fix": "Publicar solo build/dist/out — nunca el repositorio fuente.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },

    # ── Container / health / SSL ──────────────────────────────────────────────
    "container_start_failed": {
        "stage": "container_start",
        "severity": "medium",
        "detail": "El contenedor no pudo iniciarse.",
        "suggested_fix": "Revisa los logs del contenedor.",
        "retryable": True,
        "requires_user_action": False,
        "requires_admin_action": True,
    },
    "site_returns_403": {
        "stage": "health_check",
        "severity": "high",
        "detail": "El sitio respondió HTTP 403.",
        "suggested_fix": "El directorio publicado no contiene index.html o nginx bloqueó el acceso.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "site_returns_404": {
        "stage": "health_check",
        "severity": "warning",
        "detail": "El sitio respondió HTTP 404.",
        "suggested_fix": "Verificá que el build output contiene index.html.",
        "retryable": False,
        "requires_user_action": True,
        "requires_admin_action": False,
    },
    "site_returns_502": {
        "stage": "health_check",
        "severity": "high",
        "detail": "El contenedor inició pero la app no está escuchando en el puerto esperado.",
        "suggested_fix": "Verificá la configuración del puerto.",
        "retryable": True,
        "requires_user_action": False,
        "requires_admin_action": True,
    },
    "site_returns_503": {
        "stage": "health_check",
        "severity": "high",
        "detail": "El contenedor inició pero la app no está disponible.",
        "suggested_fix": "Revisá los logs del contenedor.",
        "retryable": True,
        "requires_user_action": False,
        "requires_admin_action": True,
    },
    "ssl_provisioning_timeout": {
        "stage": "ssl_check",
        "severity": "warning",
        "detail": "El certificado SSL aún no está activo.",
        "suggested_fix": "El SSL se activa automáticamente. La página estará disponible en breve.",
        "retryable": True,
        "requires_user_action": False,
        "requires_admin_action": False,
    },
    "unknown_deploy_error": {
        "stage": "unknown",
        "severity": "medium",
        "detail": "Ocurrió un error inesperado en el deploy.",
        "suggested_fix": "Reintentá el deploy. Si el error persiste, contactá soporte.",
        "retryable": True,
        "requires_user_action": False,
        "requires_admin_action": True,
    },
}


def get_matrix_entry(code: str) -> Optional[dict]:
    """Return metadata for a deploy error code, or None if unknown."""
    return MATRIX.get(code)


SUPPORTED_CODES: frozenset = frozenset(MATRIX.keys())

STAGES_ORDER = [
    "validation",
    "clone",
    "project_detection",
    "dependency_preflight",
    "dependency_install",
    "build",
    "artifact_detection",
    "publish",
    "container_start",
    "health_check",
    "ssl_check",
    "success",
]
